### ISSUE TITLE
Nothing loads when I run `ember serve -lrp 49200` [with-solution]

### ISSUE THREAD

**Issue by batwell31** [udacity/FEF-Quiz-Ember-Handlebars#2]
Many of you may have experienced the same thing, and maybe some of you haven't.  For me when I clone the repo, and run `npm install` as well as `bower install` everything goes as planned.  At least that's what I thought at first.  After running `ember serve -lrp 49200` the live reload issue is at least fixed, but none of the instructions are loaded on the screen!  

I actually experienced this issue on the last quiz, and discovered the solution to this problem: https://github.com/udacity/FEF-Quiz-Ember-Nested-Routes/issues/1

It's really simple, and all you have to do is add `"ember-inflector": "2.2.0",` to your `package.json` file, and follow up with `npm install`.  Then run the project with `ember serve -lrp 49200`, and you should see the instructions!  Hope this helps!

**Comment by chrismb008** [comment]
Yes, this is the solution! It works for me too. Thanks a lot!

**Comment by ivanjankovic** [comment]
Thanks. Took me around 3 hours to find out the solution to this issue, after numerous installs, github downloads etc.. The instructions are located at http://localhost:4200/ and the test page is http://localhost:4200/tests?nojshint&filter=Quiz . I can't believe there is novaone at Udacity that can fix this.
